# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3634357d84cdecceb83e23c409dadacb1d9dc991f6199e494ed145d1ed5e95f2ab9948d9ca033b02f0dc2dc7c9f9b1a4cfcce76d56a8f16bdc9b9301316e4a08

test:
  secret_key_base: 8f4f9810559d5cc6649cf695a050b4bd06b46f5fc32c0a0d6d4d24a8ea73cf9d8ab1f891eae4d294e83f1e75c6886c3a6a12cca7b2707dc475dcc6649935e1f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
