require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FutureCoursesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FutureCourse. As you add validations to FutureCourse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FutureCoursesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all future_courses as @future_courses" do
      future_course = FutureCourse.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:future_courses)).to eq([future_course])
    end
  end

  describe "GET #show" do
    it "assigns the requested future_course as @future_course" do
      future_course = FutureCourse.create! valid_attributes
      get :show, {:id => future_course.to_param}, valid_session
      expect(assigns(:future_course)).to eq(future_course)
    end
  end

  describe "GET #new" do
    it "assigns a new future_course as @future_course" do
      get :new, {}, valid_session
      expect(assigns(:future_course)).to be_a_new(FutureCourse)
    end
  end

  describe "GET #edit" do
    it "assigns the requested future_course as @future_course" do
      future_course = FutureCourse.create! valid_attributes
      get :edit, {:id => future_course.to_param}, valid_session
      expect(assigns(:future_course)).to eq(future_course)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FutureCourse" do
        expect {
          post :create, {:future_course => valid_attributes}, valid_session
        }.to change(FutureCourse, :count).by(1)
      end

      it "assigns a newly created future_course as @future_course" do
        post :create, {:future_course => valid_attributes}, valid_session
        expect(assigns(:future_course)).to be_a(FutureCourse)
        expect(assigns(:future_course)).to be_persisted
      end

      it "redirects to the created future_course" do
        post :create, {:future_course => valid_attributes}, valid_session
        expect(response).to redirect_to(FutureCourse.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved future_course as @future_course" do
        post :create, {:future_course => invalid_attributes}, valid_session
        expect(assigns(:future_course)).to be_a_new(FutureCourse)
      end

      it "re-renders the 'new' template" do
        post :create, {:future_course => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested future_course" do
        future_course = FutureCourse.create! valid_attributes
        put :update, {:id => future_course.to_param, :future_course => new_attributes}, valid_session
        future_course.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested future_course as @future_course" do
        future_course = FutureCourse.create! valid_attributes
        put :update, {:id => future_course.to_param, :future_course => valid_attributes}, valid_session
        expect(assigns(:future_course)).to eq(future_course)
      end

      it "redirects to the future_course" do
        future_course = FutureCourse.create! valid_attributes
        put :update, {:id => future_course.to_param, :future_course => valid_attributes}, valid_session
        expect(response).to redirect_to(future_course)
      end
    end

    context "with invalid params" do
      it "assigns the future_course as @future_course" do
        future_course = FutureCourse.create! valid_attributes
        put :update, {:id => future_course.to_param, :future_course => invalid_attributes}, valid_session
        expect(assigns(:future_course)).to eq(future_course)
      end

      it "re-renders the 'edit' template" do
        future_course = FutureCourse.create! valid_attributes
        put :update, {:id => future_course.to_param, :future_course => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested future_course" do
      future_course = FutureCourse.create! valid_attributes
      expect {
        delete :destroy, {:id => future_course.to_param}, valid_session
      }.to change(FutureCourse, :count).by(-1)
    end

    it "redirects to the future_courses list" do
      future_course = FutureCourse.create! valid_attributes
      delete :destroy, {:id => future_course.to_param}, valid_session
      expect(response).to redirect_to(future_courses_url)
    end
  end

end
