require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StudyMeetupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StudyMeetup. As you add validations to StudyMeetup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StudyMeetupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all study_meetups as @study_meetups" do
      study_meetup = StudyMeetup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:study_meetups)).to eq([study_meetup])
    end
  end

  describe "GET #show" do
    it "assigns the requested study_meetup as @study_meetup" do
      study_meetup = StudyMeetup.create! valid_attributes
      get :show, {:id => study_meetup.to_param}, valid_session
      expect(assigns(:study_meetup)).to eq(study_meetup)
    end
  end

  describe "GET #new" do
    it "assigns a new study_meetup as @study_meetup" do
      get :new, {}, valid_session
      expect(assigns(:study_meetup)).to be_a_new(StudyMeetup)
    end
  end

  describe "GET #edit" do
    it "assigns the requested study_meetup as @study_meetup" do
      study_meetup = StudyMeetup.create! valid_attributes
      get :edit, {:id => study_meetup.to_param}, valid_session
      expect(assigns(:study_meetup)).to eq(study_meetup)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StudyMeetup" do
        expect {
          post :create, {:study_meetup => valid_attributes}, valid_session
        }.to change(StudyMeetup, :count).by(1)
      end

      it "assigns a newly created study_meetup as @study_meetup" do
        post :create, {:study_meetup => valid_attributes}, valid_session
        expect(assigns(:study_meetup)).to be_a(StudyMeetup)
        expect(assigns(:study_meetup)).to be_persisted
      end

      it "redirects to the created study_meetup" do
        post :create, {:study_meetup => valid_attributes}, valid_session
        expect(response).to redirect_to(StudyMeetup.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved study_meetup as @study_meetup" do
        post :create, {:study_meetup => invalid_attributes}, valid_session
        expect(assigns(:study_meetup)).to be_a_new(StudyMeetup)
      end

      it "re-renders the 'new' template" do
        post :create, {:study_meetup => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested study_meetup" do
        study_meetup = StudyMeetup.create! valid_attributes
        put :update, {:id => study_meetup.to_param, :study_meetup => new_attributes}, valid_session
        study_meetup.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested study_meetup as @study_meetup" do
        study_meetup = StudyMeetup.create! valid_attributes
        put :update, {:id => study_meetup.to_param, :study_meetup => valid_attributes}, valid_session
        expect(assigns(:study_meetup)).to eq(study_meetup)
      end

      it "redirects to the study_meetup" do
        study_meetup = StudyMeetup.create! valid_attributes
        put :update, {:id => study_meetup.to_param, :study_meetup => valid_attributes}, valid_session
        expect(response).to redirect_to(study_meetup)
      end
    end

    context "with invalid params" do
      it "assigns the study_meetup as @study_meetup" do
        study_meetup = StudyMeetup.create! valid_attributes
        put :update, {:id => study_meetup.to_param, :study_meetup => invalid_attributes}, valid_session
        expect(assigns(:study_meetup)).to eq(study_meetup)
      end

      it "re-renders the 'edit' template" do
        study_meetup = StudyMeetup.create! valid_attributes
        put :update, {:id => study_meetup.to_param, :study_meetup => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested study_meetup" do
      study_meetup = StudyMeetup.create! valid_attributes
      expect {
        delete :destroy, {:id => study_meetup.to_param}, valid_session
      }.to change(StudyMeetup, :count).by(-1)
    end

    it "redirects to the study_meetups list" do
      study_meetup = StudyMeetup.create! valid_attributes
      delete :destroy, {:id => study_meetup.to_param}, valid_session
      expect(response).to redirect_to(study_meetups_url)
    end
  end

end
